(()=>{'use strict';
const SEMI={C:0,D:2,E:4,F:5,G:7,A:9,B:11};
const KEYS={C:[],G:['F'],D:['F','C'],A:['F','C','G'],E:['F','C','G','D'],B:['F','C','G','D','A'],'F#':['F','C','G','D','A','E'],'C#':['F','C','G','D','A','E','B'],F:['B'],'Bb':['B','E'],'Eb':['B','E','A'],'Ab':['B','E','A','D'],'Db':['B','E','A','D','G'],'Gb':['B','E','A','D','G','C'],'Cb':['B','E','A','D','G','C','F']};
function frac(s,base){if(!s)return base;if(s==='/')return base/2;if(/^\/\d+$/.test(s))return base/Number(s.slice(1));if(/^\d+$/.test(s))return base*Number(s);const m=s.match(/^(\d*)\/(\d+)$/);return m?base*(Number(m[1]||1)/Number(m[2])):base}
function keyAcc(k){k=String(k||'C').trim().split(/\s+/)[0].replace(/m$/,'');const a=KEYS[k]||[];const flat=/b/.test(k)||['F','Bb','Eb','Ab','Db','Gb','Cb'].includes(k);return{set:new Set(a),flat}}
function pitch(tok,key,measureAcc){const m=tok.match(/^([\^_=]*)([A-Ga-g])([,']*)/);if(!m)return null;let[,acc,l,oct]=m,pc=SEMI[l.toUpperCase()],o=(l===l.toLowerCase()?5:4);for(const c of oct)o+=c==="'"?1:-1;let alter=0;if(acc){if(acc.includes('='))alter=0;else alter=(acc.match(/\^/g)||[]).length-(acc.match(/_/g)||[]).length;measureAcc[l.toUpperCase()]=alter}else if(Object.prototype.hasOwnProperty.call(measureAcc,l.toUpperCase()))alter=measureAcc[l.toUpperCase()];else if(key.set.has(l.toUpperCase()))alter=key.flat?-1:1;return 12*(o+1)+pc+alter}
function parse(text){text=String(text||'').replace(/\r/g,'');const tuneStarts=[];for(const m of text.matchAll(/^X:\s*[^\n]+/gm))tuneStarts.push(m.index);if(tuneStarts.length>1)text=text.slice(tuneStarts[0],tuneStarts[1]).trim();const lines=text.split('\n');let title='ABC Import',meter=[4,4],unit=1/8,bpm=120,keyName='C',curV='V1';const voices=new Map();const voiceNames=new Map();let body=[];for(let raw of lines){let line=raw.replace(/%.*/,'').trim();if(!line)continue;let m;if((m=line.match(/^T:\s*(.*)/)))title=m[1].trim()||title;else if((m=line.match(/^M:\s*(\d+)\/(\d+)/)))meter=[+m[1],+m[2]];else if((m=line.match(/^L:\s*(\d+)\/(\d+)/)))unit=+m[1]/+m[2];else if((m=line.match(/^Q:.*?=(\d+(?:\.\d+)?)/)))bpm=+m[1];else if((m=line.match(/^K:\s*([^\s]+)/)))keyName=m[1];else if((m=line.match(/^V:\s*([^\s]+)(.*)/))){curV=m[1];const nm=m[2].match(/(?:name|nm)="([^"]+)"/);if(nm)voiceNames.set(curV,nm[1]);if(!voices.has(curV))voices.set(curV,[]);const rest=m[2].trim();if(rest&&/(?:^|\s)(?:[\^_=]*[A-Ga-gz]|\[)/.test(rest))body.push([curV,rest])}else if(/^[A-Za-z]:/.test(line)||/^%%/.test(line)){}else body.push([curV,line])}
if(!voices.size)voices.set('V1',[]);
const key=keyAcc(keyName),bar=(meter[0]*4/meter[1]);const pos=new Map([...voices.keys()].map(v=>[v,0]));const accs=new Map([...voices.keys()].map(v=>[v,{}]));
let activeV=null;for(const [defaultV,line0] of body){let v=defaultV||activeV||curV;activeV=v;if(!voices.has(v)){voices.set(v,[]);pos.set(v,0);accs.set(v,{})}let i=0,line=line0;while(i<line.length){if(/\s/.test(line[i])){i++;continue}const iv=line.slice(i).match(/^\[V:([^\]]+)\]/);if(iv){v=iv[1];activeV=v;if(!voices.has(v)){voices.set(v,[]);pos.set(v,0);accs.set(v,{})}i+=iv[0].length;continue}if(line[i]==='|'){accs.set(v,{});i++;while(i<line.length&&/[:|\[\]]/.test(line[i]))i++;continue}const rest=line.slice(i).match(/^z(\d*\/\d+|\/\d+|\/|\d+)?/);if(rest){pos.set(v,pos.get(v)+frac(rest[1],unit*4));i+=rest[0].length;continue}if(line[i]==='['&&!/^\[V:/.test(line.slice(i))){const end=line.indexOf(']',i);if(end>i){const inside=line.slice(i+1,end),lm=line.slice(end+1).match(/^(\d*\/\d+|\/\d+|\/|\d+)?/),d=frac(lm?.[1],unit*4),tokens=inside.match(/[\^_=]*[A-Ga-g][,']*/g)||[];for(const t of tokens){const p=pitch(t,key,accs.get(v));if(p!=null)voices.get(v).push([pos.get(v),d,p,80])}pos.set(v,pos.get(v)+d);i=end+1+(lm?.[0]?.length||0);continue}}
const n=line.slice(i).match(/^([\^_=]*[A-Ga-g][,']*)(\d*\/\d+|\/\d+|\/|\d+)?/);if(n){const d=frac(n[2],unit*4),p=pitch(n[1],key,accs.get(v));if(p!=null)voices.get(v).push([pos.get(v),d,p,80]);pos.set(v,pos.get(v)+d);i+=n[0].length;continue}i++}}
const tracks=[...voices.entries()].map(([id,notes],i)=>({name:voiceNames.get(id)||id,program:0,channel:i%16,notes})).filter(t=>t.notes.length);if(!tracks.length)throw new Error('Keine unterstützten ABC-Noten gefunden.');return{title,bpm,timeSignature:meter,tracks,abcSource:text,importedFrom:'ABC',barCount:Math.max(1,Math.ceil(Math.max(...tracks.flatMap(t=>t.notes.map(n=>n[0]+n[1])))/bar))}}
window.ABCImport=Object.freeze({parse});
})();