(()=>{'use strict';

const ENGINE_NAME='Composition Engine';
const ENGINE_VERSION='1.3.0';

const TECHNICAL_CONTRACT=`TECHNISCHES FORMAT (kompakt):\nNur valides JSON.\n{\"t\":\"Titel\",\"b\":BPM,\"m\":[Z,N],\"v\":[[\"Instrument\",Program,Channel,[[Takt,Position,Dauer,Pitch,Velocity,"Notenname?"],...]],...]}\nTakt beginnt bei 1, Position bei 0. Pausen durch Lücken. Jede klingende Note des Entwurfs genau einmal ausgeben. Optionaler Notenname bewahrt die beabsichtigte Schreibweise (z. B. Db4/C#4). Keine musikalischen Änderungen.`;
function createPrompts(snapshot,draft='',translated=''){
 return{
  musicalDraft:'Komponiere das verlangte Stück musikalisch frei und eigenständig. Konzentriere dich ausschließlich auf musikalische Gestalt, Verlauf, Stimmen, Rhythmus, Harmonik, Artikulation und Charakter. Denke noch NICHT an MIDI-Codierung, QN-Werte, CS-Zeilen oder ein technisches Ausgabeformat. Schreibe einen vollständigen, konkret ausnotierbaren musikalischen Entwurf, aus dem anschließend eine andere technische Instanz die MIDI-Daten erzeugen kann. Gib der Komposition einen Namen. Schreibe am Anfang zwingend einen kurzen passenden Werktitel als „Titel: …“ sowie, soweit musikalisch bestimmbar, „Tonart: …“ und „Tempo: …“ als musikalische Tempoangabe (z. B. Andante, Allegro moderato) an; dies soll die musikalische Gestaltung nicht einschränken. Mache keine Erläuterung über deine Arbeitsweise.\n\nAUFTRAG:\n'+snapshot.visibleTask,
  midiTranslation:'Übertrage den fertigen musikalischen Entwurf vollständig und unverändert in das technische Format. Keine Analyse, keine Erklärung, keine Neukomposition.\\n\\n'+draft+'\\n\\n'+TECHNICAL_CONTRACT,
  compositionIdea:'Beschreibe die fertige Komposition knapp und musikalisch konkret, ohne Bewertung oder technische Metadaten.\\n\\n'+draft
 };
}
function duplicateTitlePrompt(title,allTitles,draft){const hint=String(draft||'').slice(0,700);return'Erfinde ausschließlich einen neuen kurzen Werktitel für die bereits fertige Komposition. Keine musikalische Änderung. Antworte nur mit dem Titel.\n\nBISHERIGER TITEL:\n'+title+'\n\nBEREITS VERWENDET:\n'+allTitles.join('\n')+'\n\nKURZER KONTEXT:\n'+hint}
function makeRequest(p,m,promptText,stage){if(p==='openai')return{provider:p,model:m,url:'https://api.openai.com/v1/responses',method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer {{API_KEY}}'},body:{model:m,input:[{role:'user',content:[{type:'input_text',text:promptText}]}],store:false}};if(p==='anthropic'){const body={model:m,max_tokens:32768,messages:[{role:'user',content:promptText}]};if(/^claude-(?:sonnet|opus)-5(?:$|-)/i.test(m)&&stage==='midi_translation'){body.thinking={type:'disabled'};body.max_tokens=32768}return{provider:p,model:m,url:'https://api.anthropic.com/v1/messages',method:'POST',headers:{'Content-Type':'application/json','x-api-key':'{{API_KEY}}','anthropic-version':'2023-06-01','anthropic-dangerous-direct-browser-access':'true'},body};}const body={contents:[{role:'user',parts:[{text:promptText}]}]};if(/^gemini-3\./i.test(m)&&(stage==='midi_translation'||stage==='composition_idea_afterwards'))body.generationConfig={thinkingConfig:{thinkingLevel:'low'}};return{provider:p,model:m,url:`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(m)}:generateContent?key={{API_KEY}}`,method:'POST',headers:{'Content-Type':'application/json'},body}}
function actualRequest(s,key){const headers={...s.headers};let url=s.url;for(const k of Object.keys(headers)){if(typeof headers[k]==='string'&&headers[k].includes('{{API_KEY}}'))headers[k]=headers[k].replace('{{API_KEY}}',key)}url=url.replace('{{API_KEY}}',encodeURIComponent(key));return{url,headers,body:structuredClone(s.body)}}
function extractText(p,j){if(p==='openai'){if(typeof j.output_text==='string')return j.output_text;const parts=[];for(const item of(j.output||[]))for(const c of(item.content||[]))if(typeof c.text==='string')parts.push(c.text);return parts.join('\n')}if(p==='anthropic')return(j.content||[]).filter(x=>x.type==='text').map(x=>x.text||'').join('\n');return(j.candidates||[]).flatMap(c=>c.content?.parts||[]).map(p=>p.text||'').join('\n')}
function extractJson(text){let s=String(text||'').trim().replace(/^\`\`\`(?:json)?\s*/i,'').replace(/\s*\`\`\`$/,'').trim();try{return JSON.parse(s)}catch(_){const a=s.indexOf('{'),b=s.lastIndexOf('}');if(a>=0&&b>a)return JSON.parse(s.slice(a,b+1));throw _}}
function findScore(o){
 if(o&&Array.isArray(o.v)&&Number.isFinite(Number(o.b))){const ts=Array.isArray(o.m)?o.m:[4,4],beats=(Number(ts[0])||4)*(4/(Number(ts[1])||4));return{title:String(o.t||''),bpm:Number(o.b),timeSignature:ts,tracks:o.v.map((v,i)=>({name:String(v?.[0]||('Track '+(i+1))),program:Number(v?.[1])||0,channel:Number.isFinite(Number(v?.[2]))?Number(v[2]):i,notes:(Array.isArray(v?.[3])?v[3]:[]).map(e=>{if(!Array.isArray(e)||e.length<5)throw new Error('Ungültiges kompaktes Notenereignis.');const bar=Number(e[0]),pos=Number(e[1]),du=Number(e[2]),pi=Number(e[3]),ve=Number(e[4]);if(!Number.isInteger(bar)||bar<1||!Number.isFinite(pos)||pos<0||!Number.isFinite(du)||du<=0||!Number.isInteger(pi)||pi<0||pi>127||!Number.isInteger(ve)||ve<1||ve>127)throw new Error('Ungültiges kompaktes Notenereignis.');return[(bar-1)*beats+pos,du,pi,ve,typeof e[5]==='string'?e[5]:undefined]})}))}}
 const s=o&&o.score&&Array.isArray(o.score.tracks)?o.score:o;if(!s||!Array.isArray(s.tracks)||!Number.isFinite(Number(s.bpm)))throw new Error('Kein gültiges Partitur-Objekt gefunden.');return s
}
function findIdea(o){if(!o||typeof o!=='object')return'';for(const k of['idea','kompositionsidee','description','beschreibung','concept'])if(typeof o[k]==='string'&&o[k].trim())return o[k].trim();return''}
async function sha256Text(text){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function sha256Buffer(buf){const b=await crypto.subtle.digest('SHA-256',buf);return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function vlq(n){n=Math.max(0,Math.round(n));let b=[n&127];while((n>>=7))b.unshift((n&127)|128);return b}const strBytes=s=>[...new TextEncoder().encode(s)],u32=n=>[(n>>>24)&255,(n>>>16)&255,(n>>>8)&255,n&255],u16=n=>[(n>>>8)&255,n&255],chunk=(t,d)=>[...strBytes(t),...u32(d.length),...d];
function buildMidi(score){const ppq=480,bpm=Math.max(20,Math.min(400,Number(score.bpm)||120)),ts=Array.isArray(score.timeSignature)?score.timeSignature:[4,4],tracks=[],meta=[];const mpqn=Math.round(60000000/bpm);meta.push({tick:0,bytes:[255,81,3,(mpqn>>16)&255,(mpqn>>8)&255,mpqn&255]},{tick:0,bytes:[255,88,4,Number(ts[0])||4,Math.max(0,Math.round(Math.log2(Number(ts[1])||4))),24,8]});let last=0,md=[];for(const e of meta){md.push(...vlq(e.tick-last),...e.bytes);last=e.tick}md.push(0,255,47,0);tracks.push(chunk('MTrk',md));(score.tracks||[]).forEach((tr,ti)=>{const ch=Math.max(0,Math.min(15,Number.isFinite(Number(tr.channel))?Number(tr.channel):ti%16)),prog=Math.max(0,Math.min(127,Number(tr.program)||0)),ev=[];const name=strBytes(String(tr.name||`Track ${ti+1}`));ev.push({tick:0,p:0,b:[255,3,...vlq(name.length),...name]},{tick:0,p:1,b:[192|ch,prog]});for(const n of(tr.notes||[])){if(!Array.isArray(n)||n.length<4)continue;const st=Math.max(0,Number(n[0])||0),du=Math.max(.01,Number(n[1])||.25),pitch=Math.max(0,Math.min(127,Math.round(Number(n[2])||60))),vel=Math.max(1,Math.min(127,Math.round(Number(n[3])||80)));ev.push({tick:Math.round(st*ppq),p:2,b:[144|ch,pitch,vel]},{tick:Math.round((st+du)*ppq),p:1,b:[128|ch,pitch,0]})}ev.sort((a,b)=>a.tick-b.tick||a.p-b.p);let prev=0,d=[];for(const e of ev){d.push(...vlq(e.tick-prev),...e.b);prev=e.tick}d.push(0,255,47,0);tracks.push(chunk('MTrk',d))});return new Uint8Array([...chunk('MThd',[...u16(1),...u16(tracks.length),...u16(ppq)]),...tracks.flat()])}

function draftField(draft,label){const lines=String(draft||'').split(/\r?\n/);const prefix=String(label||'').toLowerCase()+':';for(const line of lines){const t=line.trim();if(t.toLowerCase().startsWith(prefix))return t.slice(prefix.length).trim()}return''}
function scoreBarCount(score){const ts=Array.isArray(score?.timeSignature)?score.timeSignature:[4,4],beats=(Number(ts[0])||4)*(4/(Number(ts[1])||4));let end=0;for(const tr of(score?.tracks||[]))for(const n of(tr.notes||[]))if(Array.isArray(n))end=Math.max(end,(Number(n[0])||0)+(Number(n[1])||0));return Math.max(1,Math.ceil(end/Math.max(.25,beats)))}
function providerName(p){return p==='anthropic'?'Anthropic / Claude':p==='google'?'Google / Gemini':p==='openai'?'OpenAI':String(p||'')}
function localDescription(draft){const lines=String(draft||'').split(/\r?\n/).map(s=>s.trim()).filter(Boolean);const prose=lines.find(s=>!/^([#*\-]|Titel\s*:|Tonart\s*:|Tempo\s*:|Taktart\s*:|Form\s*:)/i.test(s)&&s.length>35);return String(prose||'').replace(/[*#]/g,'').slice(0,500).trim()}
function compositionProfile(snapshot,score,draft,description){const bpm=Number(score?.bpm)||null,key=String(score?.key||score?.keySignature||score?.tonality||draftField(draft,'Tonart')||'').trim(),tempo=String(score?.tempo||score?.tempoMarking||draftField(draft,'Tempo')||'').trim(),bars=scoreBarCount(score),provider=providerName(snapshot?.provider),model=String(snapshot?.model||'').trim();const fields=[bpm?bpm+' BPM':'',tempo,key,bars+' Takte',[provider,model].filter(Boolean).join(' · ')].filter(Boolean);return{bpm,tempo,key,barCount:bars,provider,model,description:String(description||'').trim(),text:fields.join(' · ')+'\n\n'+String(description||'').trim()}}
async function compose({snapshot,key,repeatOf=null,seriesId=null,runId,now,requestModel,usedTitles=[]}){
 const startedAt=now(),run={id:runId,testId:runId,schema:'minimal-composer-diagnosis-v3',app:{name:'Minimal Composer Modular',version:'0.5.5'},seriesId,startedAt,repeatOf,contextMode:'isolated-two-stage',input:{visibleTask:snapshot.visibleTask,provider:snapshot.provider,model:snapshot.model},technicalContract:TECHNICAL_CONTRACT,events:[],aiCalls:[],requestSnapshot:structuredClone(snapshot)};
 const ev=(phase,data={})=>run.events.push({at:now(),phase,...data});
 ev('run_started',{note:'Keine frühere Unterhaltung oder Komposition wird an das Modell übertragen.'});
 const call=async(prompt,stage)=>requestModel({snapshot,key,promptText:prompt,stage,run,event:ev});
 const draft=await call(createPrompts(snapshot).musicalDraft,'musical_draft');if(!draft.trim())throw new Error('Der musikalische Entwurf ist leer.');run.musicalDraft=draft;
 const translated=await call(createPrompts(snapshot,draft).midiTranslation,'midi_translation');const obj=extractJson(translated);run.parsedModelJson=obj;ev('model_json_parsed',{stage:'midi_translation',changed:false,note:'Nur JSON geparst; keine musikalische Korrektur.'});const score=findScore(obj);run.score=score;
 const title=String(score?.title||'').trim(),allTitles=usedTitles.filter(Boolean);if(title&&allTitles.some(t=>String(t).toLocaleLowerCase('de-DE')===title.toLocaleLowerCase('de-DE'))){let nt=(await call(duplicateTitlePrompt(title,allTitles,draft),'title_renaming')).trim().replace(/^Titel:\s*/i,'').replace(/^['“”"]|['“”"]$/g,'').trim();if(!nt||allTitles.some(t=>String(t).toLocaleLowerCase('de-DE')===nt.toLocaleLowerCase('de-DE')))nt=title+' '+new Date().toLocaleDateString('de-DE');score.title=nt;ev('duplicate_title_replaced',{oldTitle:title,newTitle:nt})}
 const midiBytes=buildMidi(score),buf=midiBytes.buffer.slice(midiBytes.byteOffset,midiBytes.byteOffset+midiBytes.byteLength),midiHash=await sha256Buffer(buf);run.midi={bytes:midiBytes.byteLength,sha256:midiHash,note:'Deterministisch lokal aus den unveränderten Partiturwerten erzeugt; keine musikalische Nachbearbeitung.'};ev('midi_generated',{bytes:midiBytes.byteLength,sha256:midiHash});
 const idea=localDescription(draft);run.idea=idea;ev('composition_description_derived_local',{characters:idea.length});run.profile=compositionProfile(snapshot,score,draft,run.idea);ev('composition_profile_created',{bpm:run.profile.bpm,tempo:run.profile.tempo,key:run.profile.key,barCount:run.profile.barCount,provider:run.profile.provider,model:run.profile.model});run.completedAt=now();run.status='ok';
 return{run,midiBytes};
}

window.CompositionEngine=Object.freeze({name:ENGINE_NAME,version:ENGINE_VERSION,compose,TECHNICAL_CONTRACT,createPrompts,duplicateTitlePrompt,makeRequest,actualRequest,extractText,extractJson,findScore,findIdea,sha256Text,sha256Buffer,buildMidi});
})();
